type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  currency: String
}

type Account @table {
  user: User!
  name: String!
  type: String!
  initialBalance: Float!
  createdAt: Timestamp!
  description: String
}

type Category @table {
  user: User!
  name: String!
  type: String!
  createdAt: Timestamp!
  color: String
}

type Transaction @table {
  user: User!
  account: Account!
  category: Category
  amount: Float!
  date: Date!
  type: String!
  description: String!
  createdAt: Timestamp!
  merchant: String
}

type Budget @table {
  user: User!
  category: Category!
  amount: Float!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
  description: String
}